import Foundation

/// M12 — per-project build output and dependency folders.
///
/// Usually the single largest reclaimable category on a working machine, and the one every
/// cache-cleaner misses because it does not live in `~/Library`: it is scattered through the
/// user's own code directories. One `node_modules` on the development machine was 14 GB, with 79
/// of them in total.
///
/// Two design constraints shape this module:
///
/// - **The search has to be bounded.** Walking an entire home directory looking for
///   `node_modules` would take minutes. So search roots are the top-level folders that actually
///   look like code (they contain a git repository), and the walk stops at a fixed depth and
///   never descends into an artefact folder it has already matched.
/// - **`roots` must be knowable before the scan**, because `PathGuard` is built from it at
///   startup. Discovery is therefore shallow and deterministic enough to run twice.
public struct ProjectArtifactsModule: ScanModule {
    public init() {}

    public var descriptor: ModuleDescriptor {
        ModuleDescriptor(
            id: "projects",
            title: "Project build output",
            systemImage: "shippingbox.and.arrow.backward"
        )
    }

    /// How deep below a search root to look. Five levels reaches
    /// `~/code/client/app/packages/web/node_modules` and stops well short of walking a monorepo's
    /// entire dependency tree.
    private static let maxDepth = 5

    /// Folder names worth offering, with what it costs to get them back.
    struct Artifact {
        let name: String
        let title: String
        let note: String
        let risk: Risk
        /// A sibling file that must exist for the folder to be re-creatable. Without it, removing
        /// the folder is not a rebuild — it is a loss — so the row is not offered.
        var requiresSibling: [String] = []
    }

    static let artifacts: [Artifact] = [
        Artifact(name: "node_modules", title: "node_modules",
                 note: "npm/yarn/pnpm install restores this from the lockfile",
                 risk: .moderate,
                 requiresSibling: ["package.json"]),
        Artifact(name: "Pods", title: "CocoaPods Pods",
                 note: "pod install restores this from Podfile.lock",
                 risk: .moderate,
                 requiresSibling: ["Podfile"]),
        Artifact(name: ".next", title: "Next.js build",
                 note: "regenerated by the next build", risk: .safe),
        Artifact(name: ".nuxt", title: "Nuxt build",
                 note: "regenerated by the next build", risk: .safe),
        Artifact(name: ".svelte-kit", title: "SvelteKit build",
                 note: "regenerated by the next build", risk: .safe),
        Artifact(name: ".angular", title: "Angular cache",
                 note: "regenerated by the next build", risk: .safe),
        Artifact(name: ".parcel-cache", title: "Parcel cache",
                 note: "regenerated by the next build", risk: .safe),
        Artifact(name: ".turbo", title: "Turborepo cache",
                 note: "regenerated by the next build", risk: .safe),
        Artifact(name: ".gradle", title: "Project Gradle cache",
                 note: "the project's own build cache, separate from ~/.gradle", risk: .safe),
        Artifact(name: "target", title: "Rust/Maven target",
                 note: "cargo build or mvn package regenerates it", risk: .safe,
                 requiresSibling: ["Cargo.toml", "pom.xml"]),
        Artifact(name: "__pycache__", title: "Python bytecode",
                 note: "regenerated on import", risk: .safe),
        Artifact(name: ".venv", title: "Python virtualenv",
                 note: "re-created from requirements.txt or pyproject.toml",
                 risk: .moderate,
                 requiresSibling: ["requirements.txt", "pyproject.toml", "setup.py", "Pipfile"]),
        Artifact(name: "vendor", title: "Composer/Go vendor",
                 note: "composer install or go mod vendor restores it", risk: .moderate,
                 requiresSibling: ["composer.json", "go.mod"]),
        Artifact(name: "Library", title: "Unity Library",
                 note: "Unity rebuilds it on next open, which takes a while", risk: .moderate,
                 requiresSibling: ["ProjectSettings", "Assets"]),
        Artifact(name: "Temp", title: "Unity Temp",
                 note: "scratch output from the last Unity build", risk: .safe,
                 requiresSibling: ["ProjectSettings", "Assets"]),
        Artifact(name: "obj", title: ".NET obj",
                 note: "dotnet build regenerates it", risk: .safe),
        Artifact(name: "DerivedData", title: "Project DerivedData",
                 note: "a project-local Xcode build directory", risk: .safe)
    ]

    private static let artifactNames = Set(artifacts.map(\.name))

    /// Top-level home folders that are never code and would only slow the search down.
    private static let skippedHomeChildren: Set<String> = [
        "Library", "Applications", "Desktop", "Documents", "Downloads",
        "Pictures", "Music", "Movies", "Public", "Sites", "Parallels"
    ]

    // MARK: - Search roots

    /// Top-level folders under the home directory that contain a git repository.
    ///
    /// Using "has a repo in it" rather than a list of conventional names — `~/Developer`,
    /// `~/Projects`, `~/src` — because plenty of people keep their code somewhere else entirely;
    /// on the development machine it is `~/others`, which no such list would have guessed.
    public static func searchRoots(home: URL) -> [URL] {
        if let cached = SearchRootCache.shared.roots(for: home) { return cached }
        let discovered = discoverSearchRoots(home: home)
        SearchRootCache.shared.store(discovered, for: home)
        return discovered
    }

    private static func discoverSearchRoots(home: URL) -> [URL] {
        let fm = FileManager.default
        guard let children = try? fm.contentsOfDirectory(
            at: home,
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]
        ) else { return [] }

        return children.filter { url in
            guard !skippedHomeChildren.contains(url.lastPathComponent),
                  (try? url.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory == true
            else { return false }
            return containsRepository(url, fm: fm)
        }
    }

    /// Is this folder itself a repo, or does it hold one within two levels?
    private static func containsRepository(_ url: URL, fm: FileManager) -> Bool {
        if fm.fileExists(atPath: url.appending(path: ".git").path) { return true }
        guard let children = try? fm.contentsOfDirectory(
            at: url, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]
        ) else { return false }
        return children.contains { child in
            fm.fileExists(atPath: child.appending(path: ".git").path)
        }
    }

    public var roots: [AllowedRoot] {
        // Contents only. The search roots are the user's own code folders, and nothing should
        // ever remove one of those wholesale.
        Self.searchRoots(home: URL(fileURLWithPath: NSHomeDirectory()))
            .map { AllowedRoot($0) }
    }

    public func isAvailable(_ ctx: ScanContext) async -> Bool {
        !Self.searchRoots(home: ctx.home).isEmpty
    }

    // MARK: - Scan

    public func scan(_ ctx: ScanContext) async throws -> ScanNode {
        let roots = Self.searchRoots(home: ctx.home)
        guard !roots.isEmpty else {
            throw ScanFailure.empty("No code folders found under your home directory")
        }
        ctx.progress("Looking for build output in \(roots.count) code folder(s)")

        var found: [(artifact: Artifact, url: URL)] = []
        for root in roots {
            collect(in: root, depth: 0, into: &found)
            try Task.checkCancellation()
        }
        guard !found.isEmpty else {
            throw ScanFailure.empty("No build output or dependency folders found")
        }

        // Measured concurrently — there can be dozens, and each is an independent walk.
        let sizes = await withTaskGroup(
            of: (Int, Int64).self, returning: [Int: Int64].self
        ) { group in
            for (index, item) in found.enumerated() {
                group.addTask {
                    let size = await ctx.sizer.size(of: item.url, budget: .seconds(60))
                    return (index, size?.bytes ?? 0)
                }
            }
            var out: [Int: Int64] = [:]
            for await result in group { out[result.0] = result.1 }
            return out
        }

        // Grouped by project, because "which project is costing me 14 GB" is the question
        // someone actually has — not "how much node_modules do I have in total".
        var byProject: [URL: [ScanNode]] = [:]
        for (index, item) in found.enumerated() {
            let bytes = sizes[index] ?? 0
            guard bytes > 0 else { continue }
            let project = projectDirectory(of: item.url, roots: roots)
            byProject[project, default: []].append(ScanNode(
                id: nodeID(relativeID(item.url, home: ctx.home)),
                title: item.artifact.title,
                subtitle: item.artifact.note,
                url: item.url,
                size: bytes,
                risk: item.artifact.risk,
                action: .removePath(item.url)
            ))
        }
        guard !byProject.isEmpty else {
            throw ScanFailure.empty("No build output or dependency folders found")
        }

        let projectNodes = byProject.map { project, items in
            ScanNode(
                id: nodeID("project/" + relativeID(project, home: ctx.home)),
                title: project.lastPathComponent,
                subtitle: DeletionPlan.abbreviate(project),
                url: project,
                size: items.reduce(Int64(0)) { $0 + $1.byteCount },
                risk: .safe,
                children: items
            )
        }

        return ScanNode(
            id: descriptor.id,
            title: descriptor.title,
            subtitle: "dependency and build folders inside your own projects · "
                + "\(projectNodes.count) project\(projectNodes.count == 1 ? "" : "s")"
                + " · every one is re-created by its build tool",
            size: projectNodes.reduce(Int64(0)) { $0 + $1.byteCount },
            risk: .moderate,
            children: projectNodes
        )
    }

    /// Depth-bounded walk that never descends into an artefact it has already matched — there is
    /// no point looking for `node_modules` inside `node_modules`, and doing so is what makes a
    /// naive version of this take minutes.
    private func collect(
        in directory: URL,
        depth: Int,
        into found: inout [(artifact: Artifact, url: URL)]
    ) {
        guard depth <= Self.maxDepth else { return }
        let fm = FileManager.default
        guard let children = try? fm.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: [.isDirectoryKey],
            options: []
        ) else { return }

        for child in children {
            guard (try? child.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory == true
            else { continue }
            let name = child.lastPathComponent

            if Self.artifactNames.contains(name),
               let artifact = Self.artifacts.first(where: { $0.name == name }),
               hasRequiredSibling(artifact, beside: directory) {
                found.append((artifact, child))
                continue   // do not walk into it
            }
            // Hidden folders are skipped except the artefact names above, which are mostly
            // dot-prefixed themselves.
            if name.hasPrefix("."), !Self.artifactNames.contains(name) { continue }
            collect(in: child, depth: depth + 1, into: &found)
        }
    }

    /// `target` is only a build directory next to a `Cargo.toml` or `pom.xml`; elsewhere it could
    /// be anything. Same for `Library`, which is a Unity build folder only inside a Unity project
    /// — and is the user's own `~/Library` anywhere else.
    private func hasRequiredSibling(_ artifact: Artifact, beside directory: URL) -> Bool {
        guard !artifact.requiresSibling.isEmpty else { return true }
        let fm = FileManager.default
        return artifact.requiresSibling.contains {
            fm.fileExists(atPath: directory.appending(path: $0).path)
        }
    }

    /// The project a found artefact belongs to: its parent, unless that is a search root.
    private func projectDirectory(of artifact: URL, roots: [URL]) -> URL {
        let parent = artifact.deletingLastPathComponent()
        return roots.contains(where: { $0.standardizedFileURL == parent.standardizedFileURL })
            ? parent
            : parent
    }

    /// Stable, readable node ID derived from the path, so selection survives a rescan.
    private func relativeID(_ url: URL, home: URL) -> String {
        let path = url.path
        let prefix = home.path + "/"
        return path.hasPrefix(prefix) ? String(path.dropFirst(prefix.count)) : path
    }
}


/// Remembers which top-level folders hold code.
///
/// Three modules ask for this — project artefacts, git repositories, and the allowlist built for
/// `PathGuard` — and each answer walks the home directory probing every child for a repository.
/// Doing that three or four times per scan was a visible part of why nothing appeared for the
/// first few seconds.
///
/// Invalidated by time rather than by watching the filesystem: a folder appearing in the home
/// directory mid-session is rare, and being a minute out of date about it costs nothing.
final class SearchRootCache: @unchecked Sendable {
    static let shared = SearchRootCache()

    private let lock = NSLock()
    private var entries: [String: (roots: [URL], stamp: ContinuousClock.Instant)] = [:]
    private let lifetime = Duration.seconds(60)

    func roots(for home: URL) -> [URL]? {
        lock.lock()
        defer { lock.unlock() }
        guard let entry = entries[home.path],
              entry.stamp.duration(to: ContinuousClock.now) < lifetime
        else { return nil }
        return entry.roots
    }

    func store(_ roots: [URL], for home: URL) {
        lock.lock()
        entries[home.path] = (roots, ContinuousClock.now)
        lock.unlock()
    }
}
